---
- name: Generate runtime secrets
  set_fact:
    graylog_password_secret: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=96') }}"
    graylog_root_password_sha2: "{{ graylog_admin_password | hash('sha256') }}"

- name: Configure OpenSearch system requirements
  sysctl:
    name: vm.max_map_count
    value: '262144'
    state: present
    reload: yes
  become: yes

- name: Create data directories
  file:
    path: "{{ item.path }}"
    state: directory
    mode: '0755'
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  loop:
    - { path: "{{ graylog_data_dir }}", owner: '1100', group: '1100' }
    - { path: "{{ graylog_data_dir }}/journal", owner: '1100', group: '1100' }
    - { path: "{{ graylog_data_dir }}/config", owner: '1100', group: '1100' }
    - { path: "{{ mongodb_data_dir }}", owner: '1000', group: '1000' }
    - { path: "{{ opensearch_data_dir }}", owner: '1000', group: '1000' }
  become: yes

- name: Generate Graylog configuration
  template:
    src: graylog.conf.j2
    dest: "{{ graylog_data_dir }}/config/graylog.conf"
    owner: '1100'
    group: '1100'
    mode: '0644'
  become: yes

- name: Create Docker network
  community.docker.docker_network:
    name: "{{ docker_network_name }}"
    driver: bridge