---
- name: Deploy Graylog container
  community.docker.docker_container:
    name: graylog_server
    image: "graylog/graylog:{{ graylog_version }}"
    state: started
    restart_policy: unless-stopped
    networks:
      - name: "{{ docker_network_name }}"
    ports:
      - "9000:9000"
      - "1514:1514/udp"
      - "1514:1514/tcp"
      - "12201:12201/udp"
      - "12201:12201/tcp"
    volumes:
      - "{{ graylog_data_dir }}:/usr/share/graylog/data"
    env:
      GRAYLOG_PASSWORD_SECRET: "{{ graylog_password_secret }}"
      GRAYLOG_ROOT_PASSWORD_SHA2: "{{ graylog_root_password_sha2 }}"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
      GRAYLOG_IS_LEADER: "true"
      GRAYLOG_MONGODB_URI: "mongodb://{{ mongodb_root_username }}:{{ mongodb_root_password }}@graylog_mongodb:27017/{{ mongodb_database }}?authSource=admin"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://opensearch:9200"
      GRAYLOG_ELASTICSEARCH_VERSION: "7"
      GRAYLOG_MESSAGE_JOURNAL_ENABLED: "true"
      GRAYLOG_MESSAGE_JOURNAL_DIR: "/usr/share/graylog/data/journal"
      GRAYLOG_DATA_DIR: "/usr/share/graylog/data"
      GRAYLOG_ROOT_TIMEZONE: "UTC"
      GRAYLOG_ALLOW_LEADING_WILDCARD_SEARCHES: "true"
      GRAYLOG_ALLOW_HIGHLIGHTING: "true"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/api/system/jvm || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s

- name: Wait for Graylog readiness
  wait_for:
    port: 9000
    host: localhost
    delay: 30
    timeout: 180